name: Linux Build

on:
  push:
    branches: [ development ]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
    - name: Create executable
      uses: sayyid5416/pyinstaller@v1.8.0
      with:
        path: src
        python_ver: '3.12'
        pyinstaller_ver: 'latest'
        spec: 'QtTinySA.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'QtTinySA_Ubuntu'
